import type { Cat, Product } from '@/types';

export const cats: Cat[] = [
  {
    id: 'cat-1',
    name: '小橘',
    breed: '橘猫',
    age: '2岁',
    gender: '公',
    personality: '贪吃、亲人、活泼',
    description: '小橘是店里最贪吃的小家伙，只要你手里有零食，它就会立刻跑过来蹭你的腿。体重已经突破10斤，是店里的"重量级"明星。',
    image: 'https://placecats.com/millie/400/400',
    available: true,
  },
  {
    id: 'cat-2',
    name: '雪球',
    breed: '布偶猫',
    age: '3岁',
    gender: '母',
    personality: '温柔、粘人、安静',
    description: '雪球是一只优雅的布偶猫，蓝色的眼睛如同宝石般闪耀。它最喜欢被抱在怀里，安静地享受你的抚摸。',
    image: 'https://placecats.com/neo/400/400',
    available: true,
  },
  {
    id: 'cat-3',
    name: '大饼',
    breed: '英短',
    age: '4岁',
    gender: '公',
    personality: '慵懒、高冷、傲娇',
    description: '大饼是一只灰色的英短，圆滚滚的脸蛋是它的标志。虽然看起来高冷，但只要你耐心等待，它会慢慢靠近你。',
    image: 'https://placecats.com/bella/400/400',
    available: true,
  },
  {
    id: 'cat-4',
    name: '花花',
    breed: '三花猫',
    age: '1岁',
    gender: '母',
    personality: '好奇、调皮、灵动',
    description: '花花是店里最年轻的小猫，三色的花纹让它看起来像一幅画。它对一切充满好奇，经常追逐逗猫棒。',
    image: 'https://placecats.com/lily/400/400',
    available: true,
  },
  {
    id: 'cat-5',
    name: '煤球',
    breed: '暹罗猫',
    age: '2岁',
    gender: '公',
    personality: '话多、热情、聪明',
    description: '煤球是一只典型的暹罗猫，话特别多，经常对着客人喵喵叫。它非常聪明，能听懂自己的名字。',
    image: 'https://placecats.com/ollie/400/400',
    available: false,
  },
  {
    id: 'cat-6',
    name: '团子',
    breed: '加菲猫',
    age: '3岁',
    gender: '母',
    personality: '呆萌、安静、吃货',
    description: '团子是一只扁脸的加菲猫，呆萌的表情总能逗乐客人。它最喜欢趴在窗台上晒太阳，偶尔打个哈欠。',
    image: 'https://placecats.com/millie/400/400',
    available: true,
  },
];

export const products: Product[] = [
  {
    id: 'prod-1',
    name: '经典拿铁',
    category: 'coffee',
    price: 28,
    description: '浓郁的意式浓缩与丝滑牛奶的完美融合，入口顺滑，回味悠长。',
    image: 'https://placecats.com/neo/400/400',
    tags: ['热饮', '经典'],
  },
  {
    id: 'prod-2',
    name: '焦糖摩卡',
    category: 'coffee',
    price: 32,
    description: '香浓巧克力与咖啡的经典搭配，淋上焦糖酱，甜蜜与苦涩的完美平衡。',
    image: 'https://placecats.com/bella/400/400',
    tags: ['热饮', '甜蜜'],
  },
  {
    id: 'prod-3',
    name: '美式咖啡',
    category: 'coffee',
    price: 22,
    description: '纯粹的咖啡风味，不加任何修饰，适合喜欢原味的你。',
    image: 'https://placecats.com/lily/400/400',
    tags: ['热饮', '经典'],
  },
  {
    id: 'prod-4',
    name: '猫爪拿铁',
    category: 'coffee',
    price: 35,
    description: '店长推荐！可爱的猫爪拉花拿铁，颜值与口感并存，拍照打卡必点。',
    image: 'https://placecats.com/ollie/400/400',
    tags: ['热饮', '招牌'],
    isSeckill: true,
    seckillPrice: 19.9,
    seckillEnd: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prod-5',
    name: '抹茶拿铁',
    category: 'coffee',
    price: 30,
    description: '日式抹茶与牛奶的清新组合，茶香浓郁，口感细腻。',
    image: 'https://placecats.com/millie/400/400',
    tags: ['热饮', '清新'],
  },
  {
    id: 'prod-6',
    name: '卡布奇诺',
    category: 'coffee',
    price: 28,
    description: '厚厚的奶泡覆盖在浓缩咖啡之上，绵密如云，经典意式风味。',
    image: 'https://placecats.com/neo/400/400',
    tags: ['热饮', '经典'],
  },
  {
    id: 'prod-7',
    name: '蜜桃乌龙茶',
    category: 'drink',
    price: 25,
    description: '清新的蜜桃果香与乌龙茶底的碰撞，冰爽解渴，夏日首选。',
    image: 'https://placecats.com/bella/400/400',
    tags: ['冷饮', '果茶'],
  },
  {
    id: 'prod-8',
    name: '杨枝甘露',
    category: 'drink',
    price: 28,
    description: '芒果、西柚、椰汁的完美组合，层次丰富，清凉甜蜜。',
    image: 'https://placecats.com/lily/400/400',
    tags: ['冷饮', '招牌'],
    isSeckill: true,
    seckillPrice: 15.9,
    seckillEnd: new Date(Date.now() + 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prod-9',
    name: '柠檬气泡水',
    category: 'drink',
    price: 18,
    description: '新鲜柠檬片搭配气泡水，清爽怡人，零负担。',
    image: 'https://placecats.com/ollie/400/400',
    tags: ['冷饮', '清爽'],
  },
  {
    id: 'prod-10',
    name: '猫掌蛋糕',
    category: 'dessert',
    price: 22,
    description: '超萌猫掌造型蛋糕，草莓夹心，甜而不腻，少女心爆棚。',
    image: 'https://placecats.com/millie/400/400',
    tags: ['招牌', '可爱'],
  },
  {
    id: 'prod-11',
    name: '提拉米苏',
    category: 'dessert',
    price: 32,
    description: '经典意式甜品，马斯卡彭芝士与咖啡的层层交织，入口即化。',
    image: 'https://placecats.com/neo/400/400',
    tags: ['经典', '浓郁'],
    isSeckill: true,
    seckillPrice: 18.8,
    seckillEnd: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'prod-12',
    name: '曲奇饼干拼盘',
    category: 'dessert',
    price: 18,
    description: '多种口味手工曲奇，酥脆可口，搭配咖啡的绝佳伴侣。',
    image: 'https://placecats.com/bella/400/400',
    tags: ['酥脆', '拼盘'],
  },
];

export const banners = [
  {
    id: 'banner-1',
    title: '欢迎来到喵星咖啡',
    subtitle: '与可爱的猫咪共度悠闲时光',
    image: 'https://placecats.com/millie/1200/400',
  },
  {
    id: 'banner-2',
    title: '限时秒杀 猫爪拿铁',
    subtitle: '招牌饮品低至5折，手慢无！',
    image: 'https://placecats.com/neo/1200/400',
  },
  {
    id: 'banner-3',
    title: '新成员加入',
    subtitle: '暹罗猫"煤球"正式入驻，快来预约互动吧',
    image: 'https://placecats.com/bella/1200/400',
  },
  {
    id: 'banner-4',
    title: '下午茶套餐',
    subtitle: '任意咖啡+甜品组合立减10元',
    image: 'https://placecats.com/lily/1200/400',
  },
  {
    id: 'banner-5',
    title: '会员专属福利',
    subtitle: '注册即享首单8折优惠',
    image: 'https://placecats.com/ollie/1200/400',
  },
];

export const seckillProducts = products.filter((p) => p.isSeckill);
